# Generated by Django 5.0.1 on 2024-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artistfrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('art', models.CharField(max_length=12)),
                ('artname', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Nationality', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=21)),
                ('message', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=21)),
                ('phone', models.CharField(max_length=12)),
                ('satisfy', models.BooleanField()),
                ('msg', models.CharField(default=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=21)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=20)),
                ('country', models.CharField(default=True, max_length=12)),
                ('city', models.CharField(default=True, max_length=10)),
                ('region', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=12)),
            ],
        ),
    ]
