# Generated by Django 5.0.1 on 2024-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_payment_alter_artistfrom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phoneno',
            field=models.CharField(default='8976543245', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
